repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.23.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --recursive
          - --expand-star-imports
          - --remove-all-unused-imports
          - --ignore-init-module-imports
          - --remove-unused-variables

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
